import type { Metadata } from "next";

import { Playfair_Display } from "next/font/google";

import "./globals.css";

import { ThemeProvider } from "@wrksz/themes/next";

import SiteHeader from "@/components/page/site-header";

import SiteNavigation from "@/components/page/site-navigation";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{ children: React.ReactNode }>;

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${playfairDisplay.className} antialiased`} suppressHydrationWarning>
      <body className="mx-auto max-w-3xl px-5">
        <ThemeProvider defaultTheme="system" disableTransitionOnChange>
          <SiteHeader />
          <SiteNavigation />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
